name: file_to_markdown_converter
description: A Flutter/Dart library to convert CSV, Excel, PDF, and images (via OCR) into Markdown.
version: 1.1.0
homepage: https://github.com/hunstman11177/file_to_markdown_converter
repository: https://github.com/hunstman11177/file_to_markdown_converter
issue_tracker: https://github.com/hunstman11177/file_to_markdown_converter/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  csv: ^6.0.0
  excel: ^4.0.6
  syncfusion_flutter_pdf: ^30.2.5
  path: ^1.9.1
  meta: ^1.16.0
  google_mlkit_text_recognition: ^0.15.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  camera: ^0.11.2
  
